emsoWeb/Emso.WebUi/Controllers/ContactUsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Emso.Configuration;
using Emso.WebUi.Infrastructure.ControllerExtensibility;
using Emso.WebUi.Infrastructure.Ifaces;
using Emso.WebUi.Properties;
using Emso.WebUi.Utils;
using Emso.WebUi.ViewModels;

namespace Emso.WebUi.Controllers
{
   public class ContactUsController : CookieRouteLocalizationController
   {
      private readonly IContactSender _contactSender;
      private readonly ICredentials _credentials;
      private readonly IRecipientCollection _recipients;
      private readonly IResumeManagerRepository _resumeManager;

      public ContactUsController(IContactSender contactSender,
         ICredentials credentials,
         IRecipientCollection recipients,
         IResumeManagerRepository resumeManager)
      {
         _contactSender = contactSender;
         _credentials = credentials;
         _recipients = recipients;
         _resumeManager = resumeManager;
      }

      [HttpGet]
      public ActionResult Create()
      {
         return View(new ContactPersonViewModel());
      }

      [HttpPost]
      [ActionName("Create")]
      public async Task<ActionResult> CreateAsync(ContactPersonViewModel person)
      {
         if (!ModelState.IsValid)
         {
            return View(person);
         }
         
         var sessionId = HttpContext.GetSessionId();
         var resumeAttachments =
            await _resumeManager.GetFilesAsync(sessionId, MimeTypeId.Pdf).ConfigureAwait(false);
         var codeExamplesAttachments =
            await _resumeManager.GetFilesAsync(sessionId, MimeTypeId.Zip).ConfigureAwait(false);

         // TOREFACTOR: Отправка почты - довольно долгая операция, которая может привести к таймауту (с дальнейшей отменой операции):
         // стоит предусмотреть очередь на отправку, вместо фактического ожидания
         var contactUsResult =
            await
               _contactSender.ContactUsAsync(
                  person, resumeAttachments, codeExamplesAttachments, _credentials, _recipients).ConfigureAwait(false);

         if (contactUsResult)
         {            
            /*var deletedCount = */await _resumeManager.DeleteAsync(sessionId).ConfigureAwait(false);            
            TempData[TempDataContants.NotificationKey] = Resources.ContactUsController_SuccessfullySent;
            return RedirectToAction("Index", "Home");
         }

         ModelState.AddModelError(string.Empty, Resources.ContactUsController_ErrorSendingEmail);

         return View(person);
      }
   }
}

emsoWeb/Emso.WebUi/Controllers/VacancyController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Emso.WebUi.Infrastructure.ControllerExtensibility;
using Emso.WebUi.Infrastructure.Ifaces;
using Emso.WebUi.ViewModels;

namespace Emso.WebUi.Controllers
{
   public class VacancyController : CookieRouteLocalizationController
   {
      private readonly IJobVacancyRepository _jobVacancyRepo;

      public VacancyController(IJobVacancyRepository jobVacancyRepo)
      {
         _jobVacancyRepo = jobVacancyRepo;
      }

      [ActionName("Index")]
      public async Task<ActionResult> IndexAsync()
      {
         var vacancies = await _jobVacancyRepo.GetVacanciesAsync().ConfigureAwait(false);
         var vacancyVms =
            (from vacancy in vacancies where vacancy.IsActive select Mapper.Map<JobVacancyViewModel>(vacancy)).ToList();
         return PartialView(vacancyVms);
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            _jobVacancyRepo.Dispose();
         }

         base.Dispose(disposing);
      }
   }
}

emsoWeb/Emso.WebUi/Views/Vacancy/Index.cshtml
@model IEnumerable<Emso.WebUi.ViewModels.JobVacancyViewModel>

@{
    Layout = null;
}

<div class="panel-group" id="jobAccordion" role="tablist" aria-multiselectable="true">
    @foreach (var jobVacancyVm in Model)
    {
        Html.RenderPartial("_AccordionSummary", jobVacancyVm);
    }
</div>

emsoWeb/Emso.WebUi/Views/Vacancy/_AccordionSummary.cshtml
@using Emso.WebUi.HtmlHelpers
@using Emso.WebUi.Properties
@model Emso.WebUi.ViewModels.JobVacancyViewModel

@{
    var collPanelId = string.Format("job{0}", Model.Id);
    var hrefId = string.Format("jobHref{0}", Model.Id);
    var hrefElementId = string.Format("#{0}", hrefId);
    var emptyCollLabel = Resources.DummyColl;
}

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="@collPanelId">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#jobAccordion" href="@hrefElementId" aria-expanded="true" aria-controls="@hrefId">
                @Html.DisplayFor(modelItem => Model.Title) (@Html.DisplayFor(modelItem => Model.City))
            </a>
            <a class="pull-right" href="@Url.Action("Create", "ContactUs")">@Resources.ContactUsTitle</a>
        </h4>
    </div>
    <div id="@hrefId" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="@collPanelId">
        <div class="panel-body">
            <table class="table table-striped">
                <tbody>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.SalaryLevel)</td>
                    <td>@Html.DisplayFor(modelItem => Model.SalaryLevel)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.WorkExperience)</td>
                    <td>@Html.BuildTranslatedExperience(Model.WorkExperience)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.EmploymentType)</td>
                    <td>@Html.BuildTranslatedEmploymentType(Model.EmploymentType)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Responsibilities)</td>
                    <td>
                        @if (Model.Responsibilities.Count > 0)
                        {
                            <ul class="list-group">
                                @foreach (var responsibility in Model.Responsibilities)
                                {
                                    <li class="list-group-item">@responsibility</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <div class="text-capitalize text-info">@emptyCollLabel</div>
                        }
                    </td>

                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Requirements)</td>
                    <td>
                        @if (Model.Requirements.Count > 0)
                        {
                            <ul class="list-group">
                                @foreach (var requirement in Model.Requirements)
                                {
                                    <li class="list-group-item">@requirement</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <div class="text-capitalize text-info">@emptyCollLabel</div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.WorkingConditions)</td>
                    <td>
                        @if (Model.WorkingConditions.Count > 0)
                        {
                            <ul class="list-group">
                                @foreach (var workingCondition in Model.WorkingConditions)
                                {
                                    <li class="list-group-item">@workingCondition</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <div class="text-capitalize text-info">@emptyCollLabel</div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.RestRequirements)</td>
                    <td>

                        @if (Model.RestRequirements.Count > 0)
                        {
                            <ul class="list-group">
                                @foreach (var restRequirement in Model.RestRequirements)
                                {
                                    <li class="list-group-item">@restRequirement</li>
                                }

                            </ul>
                        }
                        else
                        {
                            <div class="text-capitalize text-info">@emptyCollLabel</div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Misc)</td>
                    <td>
                        @if (Model.Misc.Count > 0)
                        {
                            <ul class="list-group">
                                @foreach (var msc in Model.Misc)
                                {
                                    <li class="list-group-item">@msc</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <div class="text-capitalize text-info">@emptyCollLabel</div>
                        }
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>