emsoWeb/Emso.WebUi/Controllers/AdminNewsController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using AutoMapper;
using Emso.WebUi.Infrastructure;
using Emso.WebUi.Infrastructure.Auth;
using Emso.WebUi.Infrastructure.ControllerExtensibility;
using Emso.WebUi.Infrastructure.Ifaces;
using Emso.WebUi.Properties;
using Emso.WebUi.Utils;
using Emso.WebUi.ViewModels;
using EmsoHr.Entities;

namespace Emso.WebUi.Controllers
{
   [Authorize(Roles = IdentityDbInit.AdminRoleName)]
   public class AdminNewsController : CookieRouteLocalizationController
   {
      private readonly IRssFeedSource _feedSource;
      private static readonly int _PageSize = int.Parse(WebConfigurationManager.AppSettings["PageSize"]);

      public AdminNewsController(IRssFeedSource feedSource)
      {
         _feedSource = feedSource;
      }

      // GET: AdminNews
      [ActionName("Index")]
      public async Task<ActionResult> IndexAsync(int page = 1)
      {
         var newsFeeds = await _feedSource.GetAllNewsAsync().ConfigureAwait(false);
         var feedVms = newsFeeds.Select(Mapper.Map<RssFeedViewModel>).ToList();  // PERFORMANCE-NOTE: На каждой странице приходится запрашивать все данные по новостям
         var navigationVm = new NavigationViewModel<RssFeedViewModel>
         {
            PageElements = feedVms.OrderByDescending(model => model.NewsDate).Skip((page - 1)*_PageSize).Take(_PageSize),
            Navigator = new PagingNavigator
            {
               CurrentPageNumber = page,
               ItemsPerPageCount = _PageSize,
               TotalItemsCount = feedVms.Count
            }
         };

         return View(navigationVm);
      }

      // GET: AdminNews/Details/5
      [ActionName("Details")]
      public async Task<ActionResult> DetailsAsync(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var feed = await _feedSource.GetNewsAsync(id.Value).ConfigureAwait(false);
         var rssFeedVm = Mapper.Map<RssFeedViewModel>(feed);
         if (rssFeedVm == null)
         {
            return HttpNotFound();
         }

         return PartialView(rssFeedVm);
      }

      // GET: AdminNews/Create
      public ActionResult Create()
      {
         return View();
      }

      // POST: AdminNews/Create        
      [HttpPost]
      [ValidateAntiForgeryToken]
      [ActionName("Create")]
      public async Task<ActionResult> CreateAsync(
         [Bind(Include = "Title,Details,RelatedLink")] RssFeedViewModel rssFeedVm, HttpPostedFileBase imageFile)
      {
         if (!ModelState.IsValid)
         {
            return View(rssFeedVm);
         }

         var newsFeed = Mapper.Map<NewsFeed>(rssFeedVm);
         newsFeed.NewsDate = DateTime.Now;
         if (imageFile != null && imageFile.FileName != null)
         {
            var imageMimeType = imageFile.ContentType;
            if (
               !ImageProcessorUtils.ImageMimeTypes.Any(
                  mimeType => imageMimeType.Equals(mimeType, StringComparison.OrdinalIgnoreCase)))
            {
               ModelState.AddModelError(string.Empty, string.Format(Resources.NotAnImage, imageFile.FileName));
               return RedirectToAction("Create");
            }

            var imageStream = imageFile.InputStream;
            var imageBytes = await imageStream.ToByteArrayAsync().ConfigureAwait(false);
            newsFeed.ImageData = imageBytes;
            newsFeed.ImageMimeType = imageMimeType;
         }

         await _feedSource.AddNewsAsync(newsFeed).ConfigureAwait(false);
         TempData[TempDataContants.NotificationKey] = string.Format(Resources.NewsSuccessfullyCreated, newsFeed.Title);
         return RedirectToAction("Index");
      }

      // GET: AdminNews/Edit/5
      [ActionName("Edit")]
      public async Task<ActionResult> EditAsync(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var feedToEdit = await _feedSource.GetNewsAsync(id.Value).ConfigureAwait(false);
         if (feedToEdit == null)
         {
            return HttpNotFound();
         }

         var rssFeedVm = Mapper.Map<RssFeedViewModel>(feedToEdit);
         return View(rssFeedVm);
      }

      // POST: AdminNews/Edit/5      
      [HttpPost]
      [ValidateAntiForgeryToken]
      [ActionName("Edit")]
      public async Task<ActionResult> EditAsync(
         [Bind(Include = "FeedId,Title,Details,RelatedLink")] RssFeedViewModel rssFeedVm, HttpPostedFileBase imageFile)
      {
         if (!ModelState.IsValid)
         {
            return View(rssFeedVm);
         }

         var existingNews = await _feedSource.GetNewsAsync(rssFeedVm.FeedId).ConfigureAwait(false);
         var newsFeed = Mapper.Map<NewsFeed>(rssFeedVm);
         newsFeed.NewsDate = existingNews.NewsDate;
         if (imageFile != null && imageFile.FileName != null)
         {
            var imageStream = imageFile.InputStream;
            var imageBytes = await imageStream.ToByteArrayAsync().ConfigureAwait(false);
            newsFeed.ImageData = imageBytes;
            newsFeed.ImageMimeType = imageFile.ContentType;
         }
         else
         {
            newsFeed.ImageData = existingNews.ImageData;
            newsFeed.ImageMimeType = existingNews.ImageMimeType;
         }

         var isSuccessfullyUpdated = await _feedSource.UpdateNewsAsync(newsFeed).ConfigureAwait(false);
         if (!isSuccessfullyUpdated)
         {
            ModelState.AddModelError(string.Empty, Resources.FailedToUpdate);
            return View(rssFeedVm);
         }

         TempData[TempDataContants.NotificationKey] = string.Format(Resources.NewsSuccessfullyUpdated, newsFeed.Title);
         return RedirectToAction("Index");
      }

      // GET: AdminNews/Delete/5
      [ActionName("Delete")]
      public async Task<ActionResult> DeleteAsync(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var feed = await _feedSource.GetNewsAsync(id.Value).ConfigureAwait(false);
         if (feed == null)
         {
            return HttpNotFound();
         }

         var rssFeedVm = Mapper.Map<RssFeedViewModel>(feed);
         return PartialView(rssFeedVm);
      }

      // POST: AdminNews/Delete/5
      [HttpPost]
      [ValidateAntiForgeryToken]
      [ActionName("Delete")]
      public async Task<ActionResult> DeleteConfirmedAsync(int id)
      {
         var feed = await _feedSource.GetNewsAsync(id).ConfigureAwait(false);
         var rssFeedVm = Mapper.Map<RssFeedViewModel>(feed);
         var isSuccessfullyDeleted = await _feedSource.RemoveNewsAsync(feed).ConfigureAwait(false);
         if (!isSuccessfullyDeleted)
         {
            ModelState.AddModelError(string.Empty, Resources.FailedToDeleteNews);
            return View(rssFeedVm);
         }

         TempData[TempDataContants.NotificationKey] = string.Format(Resources.NewsSuccessfullyDeleted, rssFeedVm.Title);
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            _feedSource.Dispose();
         }

         base.Dispose(disposing);
      }

      [ActionName("GetNewsImage")]
      public async Task<FileContentResult> GetNewsImageAsync(int pictureId)
      {
         var newsFeed = await _feedSource.GetNewsAsync(pictureId).ConfigureAwait(false);
         var imageData = newsFeed.ImageData;
         return imageData != null ? File(imageData, newsFeed.ImageMimeType) : null;
      }
   }
}

emsoWeb/Emso.WebUi/Views/AdminNews/Create.cshtml
@using System.Web.Optimization
@using Emso.WebUi.HtmlHelpers
@using Emso.WebUi.Properties
@model Emso.WebUi.ViewModels.RssFeedViewModel

@{
    ViewBag.Title = Resources.AddNews;
}

@section ExtraScripts
{
    @Scripts.Render(BundleConfig.ScriptConstants.JqUnobtrusiveValidation)    
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"/>        
}

<div class="container">
    @using (Html.BeginForm("Create", "AdminNews", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.EditorForModel()
            @Html.BuildSubmitItem(@Resources.AddNews)
        </div>        
    }

    <div>
        @Html.BuildBackLink(Url.Action("Index"))
    </div>
</div>

emsoWeb/Emso.WebUi/Views/AdminNews/Delete.cshtml
@using Emso.WebUi.HtmlHelpers
@using Emso.WebUi.Properties
@model Emso.WebUi.ViewModels.RssFeedViewModel

<div class="container">
    <h3 class="text-center">@Resources.DeleteConfirmation</h3>
    <div>
        @Html.DisplayForModel()
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.BuildDeleteButton("pull-right")
            @Html.BuildBackLink(Url.Action("Index"))
        }
    </div>
</div>

emsoWeb/Emso.WebUi/Views/AdminNews/Details.cshtml
@using Emso.WebUi.HtmlHelpers
@model Emso.WebUi.ViewModels.RssFeedViewModel

<div class="container">
    <div>
        @Html.DisplayForModel()
    </div>
    <p>        
        @Html.BuildEditLink(Url.Action("Edit", new { id = Model.FeedId }))        
        @Html.BuildBackLink(Url.Action("Index"))
    </p>
</div>

emsoWeb/Emso.WebUi/Views/AdminNews/Edit.cshtml
@using System.Web.Optimization
@using Emso.WebUi.HtmlHelpers
@using Emso.WebUi.Properties
@model Emso.WebUi.ViewModels.RssFeedViewModel

@{
    ViewBag.Title = Resources.EditNewsTitle;
    string saveText = Resources.SaveNewsText;    
}

@section ExtraScripts
{
    @Scripts.Render(BundleConfig.ScriptConstants.JqUnobtrusiveValidation)
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"/>    
}

<div class="container">
    @using (Html.BeginForm("Edit", "AdminNews", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">            
            @Html.HiddenFor(model => model.FeedId)
            @Html.EditorForModel()
            @Html.BuildSubmitItem(@saveText)            
        </div>
    }

    <div>
        @Html.BuildBackLink(Url.Action("Index"))       
    </div>
</div>

emsoWeb/Emso.WebUi/Views/AdminNews/Index.cshtml
@using System.Web.Optimization
@using Emso.WebUi.HtmlHelpers
@using Emso.WebUi.Properties
@model Emso.WebUi.ViewModels.NavigationViewModel<Emso.WebUi.ViewModels.RssFeedViewModel>

@{
   ViewBag.Title = Resources.NewsIndexTitle;
}

<div class="container">
    <p>
        @Html.BuildCreateLink(Url.Action("Create"), Resources.CreateNewFeedLinkText)        
    </p>
    <ul class="media-list">
        @foreach (var item in Model.PageElements)
        {
            Html.RenderPartial("_NewsSummary", item);
        }
    </ul>
    <div class="text-center">
        @Html.BuildBootstrapPagination(Model.Navigator, pageNumber => Url.Action("Index", new { page = pageNumber }))
    </div>
</div>

@Scripts.Render(BundleConfig.ScriptConstants.JqMagnifier)
@Scripts.Render(BundleConfig.ScriptConstants.CrudDialog)

emsoWeb/Emso.WebUi/Views/AdminNews/_NewsSummary.cshtml
@using Emso.WebUi.HtmlHelpers
@using Emso.WebUi.Properties
@model Emso.WebUi.ViewModels.RssFeedViewModel

<li class="media">
    <div class="media-left">
        @if (!Model.HasImageData)
        {
            <img class="media-object img-responsive magnify" alt="@Resources.NoImageDummy"
                 src="~/Content/img/NoImageAvailable.png"/>
        }
        else
        {
            <img class="media-object img-responsive magnify" alt="@Model.Title"
                 src="@Url.Action("GetNewsImage", "AdminNews", new {pictureId = Model.FeedId})"/>
        }
    </div>
    <div class="media-right">
        <h3 class="media-heading">
            <a target="_blank" href="@Model.RelatedLink">@Html.DisplayFor(modelItem => Model.Title)</a> (@Html.DisplayFor(model => model.NewsDate))
            <span class="pull-right">                
                @Html.BuildEditLink(Url.Action("Edit", new { id = Model.FeedId }))
                @Html.BuildDetailsLink(Url.Action("Details", new { id = Model.FeedId }), true)
                @Html.BuildDeleteLink(Url.Action("Delete", new { id = Model.FeedId }), true)                 
            </span>
        </h3>
        
        @Html.DisplayFor(modelItem => Model.Details)
    </div>    
</li>