emsoWeb/Emso.WebUi/ViewModels/NavigationViewModel.cs
using System.Collections.Generic;
using Emso.WebUi.Infrastructure;
using Newtonsoft.Json;

namespace Emso.WebUi.ViewModels
{
   [JsonObject("navigation")]
   public sealed class NavigationViewModel<T>
   {
      [JsonProperty("elements")]
      public IEnumerable<T> PageElements { get; set; }

      [JsonProperty("navigator")]
      public PagingNavigator Navigator { get; set; }
   }
}

emsoWeb/Emso.WebUi/Controllers/AboutUsController.cs
using System.Web.Mvc;

namespace Emso.WebUi.Controllers
{
   public class AboutUsController : Controller
   {      
      public ActionResult Index()
      {
         return View();
      }
   }
}

emsoWeb/Emso.WebUi/Controllers/CareerController.cs
using System.Web.Mvc;
using Emso.WebUi.Infrastructure.ControllerExtensibility;

namespace Emso.WebUi.Controllers
{
   public class CareerController : CookieRouteLocalizationController
   {
      public ActionResult Index()
      {
         return View();
      }

      public PartialViewResult Default()
      {
         return PartialView();
      }

      public PartialViewResult AsEmployers()
      {
         return PartialView();
      }
   }
}

emsoWeb/Emso.WebUi/Controllers/NavigationController.cs
using System.Web.Mvc;
using Emso.WebUi.Infrastructure.ControllerExtensibility;

namespace Emso.WebUi.Controllers
{
   public class NavigationController : CookieRouteLocalizationController
   {
      public PartialViewResult HeaderBar()
      {
         return PartialView("HeaderBar");
      }

      public PartialViewResult LinkBar()
      {
         return PartialView("LinkBar");
      }

      public PartialViewResult FooterBar()
      {
         return PartialView("FooterBar");
      }
   }
}

emsoWeb/Emso.WebUi/Controllers/OurContactsController.cs
using Emso.Configuration;

namespace Emso.WebUi.Controllers
{
   using System.Web.Mvc;

   using Infrastructure.ControllerExtensibility;

   public class OurContactsController : CookieRouteLocalizationController
   {
      private readonly IRecipientCollection _recipients;

      public OurContactsController(IRecipientCollection recipients)
      {
         _recipients = recipients;
      }

      public ActionResult Index()
      {
         return View(_recipients);
      }
   }
}

emsoWeb/Emso.WebUi/Views/Navigation/FooterBar.cshtml
@using Emso.WebUi.Properties

<div class="container">
   <div class="emso-trend-wrapper">
      <div class="row">
         <div class="col-md-3">
            <table class="table table-striped small">
               <tr>
                  <td>
                     <div class="text-capitalize text-muted small">&copy; 2016 embedded solutions. @(Resources.AllRightsReserved).</div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
            </table>
         </div>
         <div class="col-md-3">
            <table class="table table-striped small">
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
            </table>
         </div>
         <div class="col-md-3">
            <table class="table table-striped small">
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
            </table>
         </div>
         <div class="col-md-3">
            <table class="table table-striped small">
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
               <tr>
                  <td>
                     <a href="#" class="small">Link 1</a>
                  </td>
               </tr>
            </table>
         </div>
      </div>
   </div>
</div>

emsoWeb/Emso.WebUi/Views/Navigation/HeaderBar.cshtml
@using System.Threading
@using Emso.WebUi.Properties
@using Emso.WebUi.Utils
@{
    string sideMenuPath = string.Format("{0}menucontents.html", HttpContext.Current.GetRootUrl());
    string culture = Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}

@helper Selected(string selectedCulture, string cultute)
{
    if (selectedCulture == cultute)
    {
        @:checked="checked"
    }
}

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation"
     style="background-image: url('../../Content/top-back.png')">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">EmSo</a>
        </div>
        <div class="navbar-left">
            <div class="toggler" id="emso-toggler"></div>
        </div>
        <div class="navbar-collapse collapse navbar-form navbar-right" role="form">
            @using (Html.BeginForm("SetCookieCulture", "Localization"))
            {
                @Html.AntiForgeryToken()

                <div class="cc-selector-2 form-group">
                    <input name="culture" id="en" value="en"
                           style="visibility: hidden;" type="radio" @Selected("en", culture)/>
                    <label class="drinkcard-cc visa" for="en" title="@Resources.EnglishSwitch"></label>
                    <input name="culture" id="ru" value="ru"
                           style="visibility: hidden;" type="radio" @Selected("ru", culture)/>
                    <label class="drinkcard-cc mastercard" for="ru" title="@Resources.RussianSwitch"></label>
                </div>                

                <div class="form-group">
                    <!-- Search text box -->
                    <div class="input-group stylish-input-group">
                        <input type="text" class="form-control" placeholder="@Resources.SearchPlaceholder"/>
                        <span class="input-group-addon">
                            <button type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    (function($) {
        sideviewmenu({
            menuid: "sideviewmenu",
            onopenclose: function( /*state*/) {},
            menusource: "@sideMenuPath"
        });

        $("#emso-toggler").bind("click", function( /*e*/) {
            sideviewmenu.toggle();
        });

        $("#en, #ru").click(function() {
            $(this).parents("form").submit();
        });
    })(jQuery);
</script>

emsoWeb/Emso.WebUi/Views/Navigation/LinkBar.cshtml
@using Emso.WebUi.Properties
@{
    // TOREFACTOR: Совсем нелучшее решение для получения активных ссылок
    string rawUrl = HttpContext.Current.Request.RawUrl;
    string homeActive = rawUrl == "/" ? "active" : string.Empty;
    string contactUsActive = rawUrl.EndsWith("/ContactUs/Create") ? "active" : string.Empty;
    string threeActive = string.Empty;
    string careerActive = rawUrl.EndsWith("/Career") ? "active" : string.Empty;
    string ourContactsActive = rawUrl.EndsWith("/OurContacts") ? "active" : string.Empty;
}

<div class="container">
    <ul id="gooeyMenu" class="nav nav-pills nav-justified">
        <li class="@homeActive">
            @Html.ActionLink(Resources.MainTitle, "Index", "Home")
        </li>
        <li class="@contactUsActive">
            @Html.ActionLink(Resources.AboutUsTitle, "Index", "AboutUs")
        </li>
        <li class="@threeActive">
            @Html.ActionLink(Resources.TrendsAndSolutionsTitle, "Index", "TrendsAndSolutions")
        </li>
        <li class="@careerActive">
            @Html.ActionLink(Resources.CareerTitle, "Index", "Career")
        </li>
        <li class="@ourContactsActive">
            @Html.ActionLink(Resources.OurContactsTitle, "Index", "OurContacts")
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div style="border: black 1px solid; margin-bottom: 10px;">
    </div>
</div>